Live_video
matthewfernst/Garage-UI-Mountain-Edition pull request #8
Opened 2022-12-07 05:25 UTC by matthewfernst

Added the ability to add a live stream through vite config

Signed-off-by: matthewfernst <matthew.f.ernst@gmail.com>

2022-12-07 13:39 UTC, mrrosoff requested changes

2022-12-07 13:39 UTC, mrrosoff commented on src/components/Cards/MountainInfoCard.tsx
> +                    <iframe
Can collapse this `iframe />`

2022-12-07 15:39 UTC, matthewfernst commented on src/components/Cards/MountainInfoCard.tsx
> +            <Dialog
Yeah it's like a modal but with actions built in to close. Essentially it has a full screen view of the live stream and an x in the top right to close

2022-12-10 19:10 UTC, mrrosoff approved these changes

2022-12-10 19:10 UTC, merged